package buffer.variant;

import java.io.File;
import java.io.IOException;

/**
 * This guy parses the 'masterVarBeta-..tsv.bz2' files that come from 
 * @author brendan
 *
 */
public class CompleteGenomicsVariantReader implements VariantLineReader {

	@Override
	public void setFile(File file) throws IOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public boolean advanceLine() throws IOException {
		// TODO Auto-generated method stub
		return false; //Auto-generated
	}

	@Override
	public String getCurrentLine() throws IOException {
		// TODO Auto-generated method stub
		return null; //Auto-generated
	}

	@Override
	public String getHeader() throws IOException {
		// TODO Auto-generated method stub
		return null; //Auto-generated
	}

	@Override
	public VariantRec toVariantRec() {
		// TODO Auto-generated method stub
		return null; //Autogenerated
	}

}
