package util.vcfParser;

import java.util.Map;

import buffer.variant.VariantRec;

/**
 * This interface is for things that can take a sampleMetrics map (typically generated by
 * VCFParser) and annotate a variant from it. They're used for specifying which annotations
 * to grab from a VCF that we're parsing - for instance, something like AF, which often
 * isn't there but, for some VCFs, it might be. See the VCFMetricsAnnotators class for a few
 * simple implementations. 
 * @author brendan
 *
 */
public interface VCFMetricsAnnotator {

	public void addAnnotation(VariantRec var, Map<String, String> sampleMetrics);
	
}
